### ISSUE TITLE
I found some driver files from apple

### ISSUE THREAD

**Issue by lilili87222** [DsoTsin/wintun#2]
https://www.andrew.cmu.edu/user/chunfai2/DriverStore/FileRepository/appleusb.inf_amd64_dbdeb39f14f38d7a/

**Comment by lilili87222** [comment]
Can this replace wetest's driver?

**Comment by doronz88** [comment]
This doesn't seem to be CDC NCM driver

**Comment by DsoTsin** [comment]
> Can this replace wetest's driver?

No
